### ISSUE TITLE
When vite config resolve.alias is array have a bug 

### ISSUE THREAD

**Issue by songyihong** [vite-plugin/vite-plugin-optimizer#3]
if (typeof config.resolve.alias === 'object') {
      config.resolve.alias = Object
      .entries(config.resolve.alias)
      .reduce((memo, [find, replacement]) => memo.concat({ find, replacement }), []);
}

In your code, when resolve.alias is array，resolve.alias will be inoperative

**Comment by caoxiemeihao** [comment]
😄 Thanks for your feedback!
