### ISSUE TITLE
vite4 require is not defined

### ISSUE THREAD

**Issue by wwjll** [vite-plugin/vite-plugin-optimizer#7]
vite4 require is not defined when this plugin is configured , this is my `vite.config.ts
```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

import optimizer from "vite-plugin-optimizer";

let getReplacer = () => {
  let externalModels = ["os", "fs", "path", "events", "child_process", "crypto", "http", "buffer", "url", "better-sqlite3", "knex", "stream"];
  let result = {};
  for (let item of externalModels) {
    result[item] = () => ({
      find: new RegExp(`^${item}$`),
      code: `const ${item} = require('${item}');export { ${item} as default }`,
    });
  }
  return result;
};

export default defineConfig({
  plugins: [
    optimizer(getReplacer()),
    vue()
  ],
})
```

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reporduction repo?

**Comment by yejimeiming** [comment]
Can you provide a minimal reporduction repo?

**Comment by wwjll** [comment]
> Can you provide a minimal reporduction repo?
Hi there, I am trying to use some Nodejs builtin module in browser and [repo](https://github.com/wwjll/Vite-plugin-optimizer-test.git), I try to do
` console.log(fs.writeFileSync)` in App.vue and get this error.

**Comment by yejimeiming** [comment]
<img width="400" alt="image" src="https://github.com/vite-plugin/vite-plugin-optimizer/assets/135394392/dbaca9e8-ffd9-49cb-a527-abca5ef231c4">

<img width="400" alt="image" src="https://github.com/vite-plugin/vite-plugin-optimizer/assets/135394392/15b75944-73a0-44f0-b51c-09107785fa6c">

I'm not sure waht you're trying to do, but there's no way the `fs` module will work in a Browser.
